### ISSUE TITLE
CheckParameterValue numba

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/nutpie#3]
Just noticed that the numba funcify just gets rid of bound checks. 

In PyMC, by default, we replace it by `-inf` switches [here](https://github.com/pymc-devs/pymc/blob/a568762cd2fd0c0d19d8c0700a5e64374f1639b8/pymc/aesaraf.py#L881). This will obviously be slower and unnecessary for most (well) parametrized models. Just wanted to ask if it was a conscious choice.

https://github.com/aseyboldt/nutpie/blob/6f22b171ddc913e9b6b0cc16e1d25b5148db8614/nutpie/compile_pymc.py#L15

**Comment by aseyboldt** [comment]
By bounds checks you mean domain checks, right? Array accesses should still be checked, right?
But other than that, yes this should be fixed properly. I also thought there was a switch in `pm.Model` that disabled those domain checks, but it didn't seem to do anything.

**Comment by ricardoV94** [comment]
It's here: https://github.com/pymc-devs/pymc/blob/a568762cd2fd0c0d19d8c0700a5e64374f1639b8/pymc/aesaraf.py#L1016

**Comment by aseyboldt** [comment]
Hm, maybe I should call that to generate the logp function.
This also reminds me that the rng code won't work properly if it ends up in the dlogp function (although I can't think of a usecase where it legitimately would end up there), because updates to shared variables won't work, and if they did they wouldn't be threadsafe.

**Comment by aseyboldt** [comment]
nutpie is now using the pymc rewrite if bounds checks are off. (since #42)
